import re

MAX_TEXT_LENGTH = 1000
MAX_BODY_BYTES = 1024 * 128
DOWNLOAD_COOLDOWN_SECS = 90.0
ALL_VOICES_CACHE_TTL_SECS = 3600.0
VOICE_ID_RE = re.compile(r"[a-zA-Z0-9_\-]+")
DEFAULT_SENTENCE_SILENCE = 0.0
DEFAULT_LENGTH_SCALE = 1.0
DEFAULT_NOISE_SCALE = 0.667
DEFAULT_NOISE_W_SCALE = 0.8
DEFAULT_VOLUME = 1.0
DEFAULT_NORMALIZE_AUDIO = True
MAX_SENTENCE_SILENCE = 5.0
MIN_LENGTH_SCALE = 0.25
MAX_LENGTH_SCALE = 4.0
MIN_NOISE_SCALE = 0.0
MAX_NOISE_SCALE = 2.0
MIN_NOISE_W_SCALE = 0.0
MAX_NOISE_W_SCALE = 2.0
MIN_VOLUME = 0.0
MAX_VOLUME = 4.0
